# como rodar:
# docker-compose up --build

version: "3.8"

services:
  app1:
    build: .
    container_name: app1
    ports:
      - "8001:8000"
  
  app2:
    build: .
    container_name: app2
    ports:
      - "8002:8000"

  nginx:
    image: nginx:latest
    container_name: nginx_lb
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2